services:
  devcontainer:
    image: dev2dy/tmux-neovim
    container_name: tmux-neovim-devcontainer
    build:
      dockerfile: Dockerfile
      context: .
      args:
        UID: 1000
        GID: 1000
        UNAME: user
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    volumes:
      - ${HOME}/Projects:/workspace
      - ${HOME}/.ssh:${HOME}/.ssh:ro  # To be able to git push from container
