services:
  devcontainer:
    image: dev2dy/tmux-neovim
    container_name: tmux-neovim-devcontainer
    hostname: devcontainer
    build:
      dockerfile: Dockerfile
      context: .
    user: ${UID}:${GID}
    group_add:
      - ${DOCKER_GID}
      - ${WHEEL_GID}
    working_dir: ${HOME}
    environment:
      # Semilcolon separated variable e.g: "python3;kubectl" (See available packages in /install_packages)
      INSTALL: "python3;kubectl"
      DISPLAY: ${DISPLAY}
    restart: unless-stopped
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    volumes:
      - ${HOME}:${HOME}
      - ${HOME}/.gitconfig:${HOME}/.gitconfig:ro      # To be able to git push from container
      - ${HOME}/.ssh:${HOME}/.ssh:ro                  # To be able to git push from container
      - ${HOME}/.kube:${HOME}/.kube                   # To be able to access kubernetes clusters
      - /var/run/docker.sock:/var/run/docker.sock:ro  # To be able to access host docker daemon from container
      - /tmp/.X11-unix:/tmp/.X11-unix:ro              # To be able to copy to clipboard
      - /etc/group:/etc/group:ro                      # For correct handle of user and groups (only if "group_add" parameter used)
      - /etc/passwd:/etc/passwd:ro                    # For correct handle of user and groups (only if "user" parameter used)
      - /etc/shadow:/etc/shadow:ro                    # For sudo (only if "user" parameter used)
